[project]
name = "streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
packages = [
    "streamlit>=1.51.0",
    "pandas>=2.3.3"
]
